### ISSUE TITLE
Every page is ignored, error message 0x80042006

### ISSUE THREAD

**Issue by Errand0596** [alxnbl/onenote-md-exporter#101]
**Describe the bug**
I am having the same issue as reported in the bellow issue. Every page is ignored, and displays error 0x80042006. I am selecting Joplin format, but this also occurs with the Markdown option. 
https://github.com/alxnbl/onenote-md-exporter/issues/9

**To Reproduce**
This occurred with my primary notebook, however, someone suggested trying with another small test notebook, which I did, an I got the same result. I feel like it must be related to my specific OS install or work environment. 

Steps to reproduce the behavior.
I used and ran the program like normal each time, specifically version 1.4
![image](https://github.com/alxnbl/onenote-md-exporter/assets/120143978/46a8dc4b-669d-4727-ac6f-076560e76e25)
This occurs on the 3 notebooks listed in the screenshot, so I do not think its the notebooks themselves.

Ideally, export a basic OneNote notebook (.onepkg) that can be use to reproduce the issue. Tutorial to export .onepkg file is [available here](/doc/notebook-onepkg-export.md).

Its a pain in the ass to upload in-compatible file types to github. My test notebook was created, with two pages of plain text that each say "test" I can figure something out if someone really wants me to. I don't think this has anything to do with the notebook(s) I'm using. 

**Expected behavior**
Export my notebook  to joplin format :(

**Logs**

[13:15:57 INF] -----------------------
[13:15:57 INF] - OneNote Md Exporter -
[13:15:57 INF]        v1.4.0.0
[13:15:57 INF] -----------------------

[13:15:57 INF] Before continue, please verify that :

* OneNote and Word of Office suite are correctly installed - Yes they should be, I've been using them all for a while
* OneNote is running and the Notebooks to export are opened - Yes
This tool and OneNote are started with normal priviledges (NOT as an administrator) - Yes

Known limitations:
* The free application 'One Note For Windows' is not supported - Not using free version
* File attachments with certain extensions are not exported, including : wma, wmv, mpg, svg, mp3 (Issue #39) - Not relevant, fails with plaintext notebooks
* Password protected sections are not exported, except if they are unlocked before the export - N/A
* Hand-writting text is not exported - N/A

/!\ Allways keep a backup of your OneNote notebooks in case you discover later that some data is missing in the export /!\

[13:15:57 INF] Press [Enter] to continue...
[13:15:59 INF] 
***************************************
[13:15:59 INF] 3 notebook(s) found(s).
[13:15:59 INF] ***************************************

[13:15:59 INF] Please enter the notebook number to export, or a coma separated list of value (ex: "2,3,4") : 
[13:15:59 INF] [0] Export all notebooks
[13:15:59 INF] [1] IT Main
[13:15:59 INF] [2] Test
[13:15:59 INF] [3] itmain2
[13:16:05 INF] 
Please choose export format: 
[13:16:05 INF] [1] Markdown
[13:16:05 INF] [2] Joplin Raw Folder
[13:16:08 INF] 
[13:16:08 INF] Open advance settings editor ?
[yes] or [Enter] to continue with current settings
[13:16:09 INF] 
***************************************
[13:16:09 INF] Start exporting notebook: Test
[13:16:09 INF] ***************************************
[13:16:09 INF] --> Found 1 sections and sections groups

[13:16:09 INF] Start processing section (1/1) :  Test\New Section 1\New Section 1
[13:16:09 INF]    Page 1/2 : Test
[13:16:09 WRN] Page 'Test\New Section 1\Test': Error during processing of page Test [26996600a40d46ae9958b8185ae8b685]. Page ignored. Error message : 0x80042006
[13:16:09 INF]    Page 2/2 : Test
[13:16:09 WRN] Page 'Test\New Section 1\Test': Error during processing of page Test [9406d3d1febe48a99b5df7d42ca567a5]. Page ignored. Error message : 0x80042006
[13:16:09 INF] 
[13:16:09 WRN] --> WARNING: export of your notebook has ended with 2 page(s) on error.\You can find more details in the log file 'logs.txt'.\nExport folder : 'C:\Users\nicholas\Downloads\OneNoteMdExporter.v1.4.0\Exports\joplin-raw-dir\Test-20240510 13-16'
[13:16:09 INF] 
[13:16:09 INF] Press [Enter] to continue...
[13:17:21 INF] 
Press any key to exit...

⚠️ Ensure that the log file do not contain any personal data ⚠️

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : v1.4.0, but I also tried v0.4.0Beta1 and v0.4.0Beta2 which claim to have had the fix for this exact issue. 
 - Windows version : Windows 11 Pro 64 bits
 - Office Version : C:\Program Files\Microsoft Office\root\Office16 Office16, 64bit

**Additional context**
I tried multiple versions of the software, and I do get a different error with a very older version, but it still fails.

![image](https://github.com/alxnbl/onenote-md-exporter/assets/120143978/f34525ff-fe6f-434a-bb62-9c9a3f296c3e)

I also tried installing a bunch of .NET runtimes, pretty much every version from 3-8. I also installed other microsoft visual c++ redestributables. 

I'm really hoping to get help, I want to break free of the Microsoft ecosystem, and years of notes are in here. I've been trying to move out to Joplin forever.

Thank you all

**Comment by alxnbl** [comment]
Hey @Errand0596 , have you tried to uninstall and reinstall office ? Have you Onenote and Word installed and correctly working ? Have you started OneNote before running the tool ?

As a last solution you can try to export and then import your notebooks on an other computer with office, if you can find one.

**Comment by Errand0596** [comment]
@alxnbl Thank you very very much for the quick response, and for your software. 

I was able to get it to export by jumping onto an older machine that had an image from 2021, it worked the first time. 
Sadly, now the images "resources" did not export correctly. They are standard images, .pngs and .jpegs and the like. They are mostly from Windows screenshots made with the Snip tool. Please see an example
![7e000d3d55974402a1bc38c081a7408d](https://github.com/alxnbl/onenote-md-exporter/assets/120143978/26c5c93c-6f34-4ca9-8d97-0d469d2c2a3b)
![3c35f910115f4ab4b4575219bdfbf404](https://github.com/alxnbl/onenote-md-exporter/assets/120143978/39f022f5-1898-4538-bd4d-a678bbec65c3)
![51ff9a4e20a04d6bb3f73288e2cdf313](https://github.com/alxnbl/onenote-md-exporter/assets/120143978/e362677b-bc09-468b-b2d8-f88aec945635)

**Comment by Errand0596** [comment]
@alxnbl I tried an additional run, and now about 60% of my images exported correctly. Maybe thats as good as it will get? I am open to any and all suggestions. I had zero errors in both runs. And again, these are not exotic file types. Thank you.

**Comment by alxnbl** [comment]
There is no open issue or limitation I am aware of that can explain the behavior.
You can try to duplicate your notebook and remove pagea to make a minimal notebook that allow to reproduce the bug and share it here.

You can also try to export and then reimport your notebook and check images, to verify that the error do not comes from a domaged notebook file.

**Comment by Errand0596** [comment]
Thank you, I will try some different things since it seems to be on my end or the notebook data itself now.
