### ISSUE TITLE
Can you add an option, converting numbered list in onenote to headings in md?

### ISSUE THREAD

**Issue by SuperFelix117** [alxnbl/onenote-md-exporter#15]
Can you add an option, converting numbered list in onenote to headings in md?
example:
1.h1
     A.h2
           i)h3
                      -apple
                      -orange
                      -banana

becomes

#h1
##h2
###h3
*apple
*orange
*banana

Please kindly explore the posibility! Thank You!!

**Comment by alxnbl** [comment]
Currently conversion into Md is done by PanDoc. Consequently, to support this feature we need to find how to make PanDoc do it during its conversion.

**Comment by SuperFelix117** [comment]
Underestood. Thank you alxnbl!
