### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by eromawyn** [alxnbl/onenote-md-exporter#16]
**Describe the bug**
All I get when I run the pre-compiled executable is an error message about a COM class not registred. Onenote for Windows 10 is installed and running.

Unhandled exception. System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {D7FAC39E-7FF1-49AA-98CF-A1DDD316337E} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
   at alxnbl.OneNoteMdExporter.Program.Main() in C:\Src\GitH\onenote-md-exporter\src\Program.cs:line 21

**To Reproduce**
![image](https://user-images.githubusercontent.com/17792937/109421265-422f5c00-79df-11eb-948a-6dd1eed3a418.png)

**Expected Behaviour**
A running program, or at least, a more user friendly message telling what I did wrong.

**Desktop (please complete the following information):**
 - Windows version : 10 with all standard updates.
 - Office Version : not installed. I don’t use it. Shall I install it ?
 -  [Optional] PanDoc Version : 2.11.4 (installed through chocolatey).

**Comment by alxnbl** [comment]
Hello, sorry but as said in project home page : `The tool requires Microsoft Office to be installed, OneNote for Windows 10 is not supported.`

Maybe you can fiund around you someone with an Office installation ? Or you can have a look on other migration tools that use Microsoft Office "cloud" (online grap api) and do not require an Office installation.

**Comment by eromawyn** [comment]
In that case, as I am pretty sure I’m not the only one who will hit this exception, the program should catch it and give an explicit error message, something like : « _Can’t connect to COM. Did you check that MS Office is installed ?! The tool requires Microsoft Office to be installed, OneNote for Windows 10 is not supported._  ».

**Comment by alxnbl** [comment]
Solved in version 1.0. Cf #21
