### ISSUE TITLE
 Page ignored. Error message : Class not registered - v0.4.0 Beta2

### ISSUE THREAD

**Issue by neverthejetsetter** [alxnbl/onenote-md-exporter#19]
So I've downloaded and attempted to use both Beta versions today and I am getting the following errors with v0.4.0 Beta2.

***************************************
Start exporting notebook: Dummy Notebook
***************************************
--> Found 2 sections and sections groups

Start processing section (1/2) :  Dummy Notebook\New Section 1\New Section 1
   Page 1/1 : Dummy Note
Error during processing of page Dummy Note [7f29771d55314b1bb48c59d07b5491da]. Page ignored. Error message : Class not registered

Class not registered

Start processing section (2/2) :  Dummy Notebook\New Section 2\New Section 2
   Page 1/1 : This is a New Page
Error during processing of page This is a New Page [e971b572dcd54364a70610ab58781609]. Page ignored. Error message : Class not registered

Class not registered

--> Notebook export successful
Export folder : 'D:\Workfiles\Export Folder\Joplin Notes\OneNote to Joplin Beta2\Dummy Notebook'

I do really appreciate all the work you're doing on this. Wish I knew how to program so I could help!

Again I'm running Windows 10, OneNote 2016 (Stand Alone) 64 bit. I have plenty of free memory.

**Comment by alxnbl** [comment]
Hi, I have an idea of something to try on my side. I will send you a test version by the end of the week.

Meanwhile, could you confirm that  :
- You are not running the export tool as an Administrator
- You have MS Word Installed, not only OneNote. And if you start Word that there is no window that pop (like "do you want to use MS word as your default software". Indeed, I recently understand that OneNote is relying to Word app to execute the export operation requested by the export tool.

Thanks

**Comment by neverthejetsetter** [comment]
It works!

I believe it was because I did not have the full version of Office 2016 installed (as previously mentioned I was only running the stand alone version of OneNote 2016 Home and Student). It took a little while to locate a full 2016 version of Office Home and Student (because it's not available directly for purchase from Microsoft any longer). Unfortunately, the easiest method was to purchase a product key (and digital download/instructions) for about $40 from a 3rd party seller. Which I promptly did this morning.

Anyway, after I had Office 2016 installed, I ran the v0.4.0 Beta1 x86 version (not as administrator) and everything exports perfectly. And on the Joplin side it imports beautifully!

I'm very impressed with your hard work and I appreciate all your help! Thank you!

**Comment by neverthejetsetter** [comment]
Update: I just noticed that To-Dos/Check Boxes in OneNote are not migrating as a Checkbox in Joplin.

If a note in OneNote contains list items in a To-Do/Checkbox format, they get imported as a block of text, with no space where the checkbox would have been. Example:
In One Note:
- [ ] Item One
- [ ] Item Two
- [ ] Item Three

Will look like this in Joplin:
Item OneItem TwoItem Three

Hope that makes sense. I can create a new issue for this if you think it's necessary.

**Comment by alxnbl** [comment]
Great that it works. I will add in the documentation that the tool requires Word and add an explicit error message in a future release.
About issue with item lists, I already knew this limitation, but yes could you please create an issue. No idea how it can be solved but I will have a look in the future.
