### ISSUE TITLE
Images are not assigned correctly

### ISSUE THREAD

**Issue by letscho123** [alxnbl/onenote-md-exporter#24]
Hello,

I was one of the cases, where the exporter did not work until version 0.4. Now it works, but images are not exported correctly.

I made a very simple test file, with figures and a little text. When I run the exporter and choose Joplin format, everything seems to work fine. However, the resources folder is empty and the images are referred to in the MD file as
`![](tmp/media/image1.png)`
or
`![- Shortcut single\_pass• Spyder m855-reS이l ZO 0 LibreOffice mtof VidyoConn.. Word 2016 SIMION 2020 Sublime Text SumatraPDF thorlabs Notepad+ ](tmp/media/image2.png)`
with some image description. The text and sections are exported correctly.

Interestingly, with a larger notebook including many images, the images were in the resources folder with correct names. Nevertheless, they were referred to in the same way in the MD file 
`![](tmp/media/image1.png)`

Also with the markdown option, the resources folder stays empty, but Word files with the whole Onenote pages are created (maybe this is intentional).

I am running on Windows 10, Onenote 365 and stable release 0.4.0

**Comment by alxnbl** [comment]
Hello @letscho123 , can you join a sample notebook that I can use to reproduce the issue ?

**Comment by letscho123** [comment]
Here you go. Thanks!

[test.zip](https://github.com/alxnbl/onenote-md-exporter/files/6097770/test.zip)

**Comment by alxnbl** [comment]
Hey @letscho123 , I finally give a look to your issue but I have not been able to reproduce it using your NoteBook : 

![image](https://user-images.githubusercontent.com/15685554/114933897-85337a80-9e39-11eb-9814-b4c894534cce.png)

![image](https://user-images.githubusercontent.com/15685554/114933915-8c5a8880-9e39-11eb-9cf4-f41fb7db0387.png)

![image](https://user-images.githubusercontent.com/15685554/114933933-9086a600-9e39-11eb-91bd-efd6989fbd16.png)

Your bug may have been caused by something specific to your configuration. Could you try again and join the `alxnbl.OneNoteMdExporter.log` log file please ?

**Comment by letscho123** [comment]
Thanks for coming back to me!

Unfortunately, I encountered a new issue. I cannot export anything anymore, I get following messages during the process:
![Screenshot from 2021-04-17 11-46-02](https://user-images.githubusercontent.com/78268466/115109080-127aea00-9f74-11eb-85c3-27864bd92d06.png)
and here is the log:

> [11:47:00 INF] Start exporting notebook: My Notebook
> [11:47:00 INF] ***************************************
> [11:47:00 INF] --> Found 1 sections
> 
> [11:47:00 INF] Start processing section (1/1) :  My Notebook\Quick Notes/Quick Notes
> [11:47:01 INF]    Page 1/2 : OneNote: one place for all of your notes
> [11:47:03 ERR] Error during processing of page OneNote: one place for all of your notes [1360ce2e9ac34809bc7f6b12e46390d8]. Page ignored. Error message : 0x80042006
> [11:47:03 INF]    Page 2/2 : OneNote Basics
> [11:47:06 ERR] Error during processing of page OneNote Basics [dd42013452154a67a08b8996d18bbc4c]. Page ignored. Error message : 0x80042006
> [11:47:06 INF] 
> [11:47:06 INF] --> Notebook export successful
> Export folder : 'C:\Users\username\Downloads\OneNoteMdExporter.v0.4.0\My Notebook'

This problem persists for all notebooks independently of Markdown or Joplin conversion. Since I don't use this PC, it might be related to Windows updates. I did not change any settings compared to last time, where the export was successful.

**Comment by alxnbl** [comment]
Hi, I have already observed that if for any reason a popup is opened at Word startup, then an error is raised during page export.
Cloud you try to first start MS Word and ensure no popup is opening (check "Don't show this msg again"), and next try to export your notes a new time. 🤞

**Comment by letscho123** [comment]
HI, thanks with this workaround it works again.

This is the log, which looks normal:
> [15:44:18 INF] Start exporting notebook: test
> [15:44:18 INF] ***************************************
> [15:44:18 INF] --> Found 1 sections and sections groups
> 
> [15:44:18 INF] Start processing section (1/1) :  test\Section\Section
> [15:44:18 INF]    Page 1/2 : test
> [15:44:20 INF]    Page 2/2 : hasdf
> [15:44:22 INF] 
> [15:44:22 INF] --> Notebook export successful
> Export folder : 'C:\Users\username\Downloads\OneNoteMdExporter.v0.4.0\test'
> [15:44:22 INF] 
> [15:44:22 INF] 
> Press a key to exit...

I attached the individual files from Joplin (first 4 files) and Markdown export from the same notebook I sent you before. The resources folder is always empty.
[4c3cf2f41ddc497f915b0ce057ba2496.md](https://github.com/alxnbl/onenote-md-exporter/files/6329348/4c3cf2f41ddc497f915b0ce057ba2496.md)
[7a2afdd4b14941ba860c3ad12cfa3efa.md](https://github.com/alxnbl/onenote-md-exporter/files/6329349/7a2afdd4b14941ba860c3ad12cfa3efa.md)
[990ff2cf667f46489d649aaf3f9f2d42.md](https://github.com/alxnbl/onenote-md-exporter/files/6329350/990ff2cf667f46489d649aaf3f9f2d42.md)
[a3a24d9eae8148409fd2f48ed5cfe5e2.md](https://github.com/alxnbl/onenote-md-exporter/files/6329351/a3a24d9eae8148409fd2f48ed5cfe5e2.md)
[hasdf.docx](https://github.com/alxnbl/onenote-md-exporter/files/6329352/hasdf.docx)
[hasdf.md](https://github.com/alxnbl/onenote-md-exporter/files/6329353/hasdf.md)
[test.docx](https://github.com/alxnbl/onenote-md-exporter/files/6329354/test.docx)
[test.md](https://github.com/alxnbl/onenote-md-exporter/files/6329355/test.md)

**Comment by letscho123** [comment]
With version 0.5 the problem is solved and all figures are exported correctly. Thanks a lot for your work!

**Comment by alxnbl** [comment]
Nice 👍🏻
