### ISSUE TITLE
How to support this project?

### ISSUE THREAD

**Issue by CalvinCorp** [alxnbl/onenote-md-exporter#26]
Howdy Team,

Thanks for this project, it really made my life 100% better as now I have fully migrated over 1GB+ of OneNote notebooks into Joplin. Joplin is way better than OneNote nowadays and I happy that your application made it possible.

How can someone donate to your team or project?

Thanks!

**Comment by alxnbl** [comment]
Hello @CalvinCorp, and thank you for your post. It is very encouraging to see that the tool is being used and can be of great value!
I have developed it on a voluntary basis, so I do not wish to accept donations. So a send a message like you did and star the repo is already great. But if you haven't already, I would suggest donating to Laurent, the developer of Joplin, who I think needs support to keep developing his awesome app! https://joplinapp.org/donate/.

I
