### ISSUE TITLE
Headings formating gets ignored

### ISSUE THREAD

**Issue by raf64flo** [alxnbl/onenote-md-exporter#28]
Hi, 

First, thanks for such tool, which allows to get away from Microsoft system, that is a good step on its own!

**Describe the bug**

Exporting a basic Note book misses the headings formatting. See generated folder in [onenote-md-exporter-test-generated.zip](https://github.com/alxnbl/onenote-md-exporter/files/6311148/onenote-md-exporter-test-generated.zip).

**To Reproduce**

Run the tool (v0.4.0.5) on the attached OneNote notebook (see [onenote-md-exporter-test.zip](https://github.com/alxnbl/onenote-md-exporter/files/6311147/onenote-md-exporter-test.zip)).

**Expected behavior**

Headings should be kept as Markdown headings using sharps. Neither in Joplin folder nor in Markdown folder the headings are generated.

**Logs**
See [alxnbl.OneNoteMdExporter.log](https://github.com/alxnbl/onenote-md-exporter/files/6311150/alxnbl.OneNoteMdExporter.log).

**Desktop (please complete the following information):**
 - Windows version : Windows 10 64 bits
 - Office Version : Office 2016 64 bits
 -  PanDoc Version : 2.13

**Attachments:**
[onenote-md-exporter-test.zip](https://github.com/alxnbl/onenote-md-exporter/files/6311147/onenote-md-exporter-test.zip)
[onenote-md-exporter-test-generated.zip](https://github.com/alxnbl/onenote-md-exporter/files/6311148/onenote-md-exporter-test-generated.zip)
[alxnbl.OneNoteMdExporter.log](https://github.com/alxnbl/onenote-md-exporter/files/6311150/alxnbl.OneNoteMdExporter.log)

**Comment by alxnbl** [comment]
This issue should now be solved. Please reopen the issue if it is not. Thanks
