### ISSUE TITLE
One Note Interop not detecting my notebooks

### ISSUE THREAD

**Issue by nosmalldreams** [alxnbl/onenote-md-exporter#30]
OneNote Interop seems not to be detecting my notebooks. In debug mode on a Windows 10 PC with OneNote for Windows 10, Visual Studio 2019, version 16.9.3 I find that the call to oneNoteApp.GetHierarchy in GetNotebooks returns an XML String without any notebooks: "<?xml version=\"1.0\"?>\r\n<one:Notebooks xmlns:one=\"http://schemas.microsoft.com/office/onenote/2013/onenote\"><one:UnfiledNotes ID=\"{_A GUID_}{1}{B0}\"/></one:Notebooks>\r\n".  

Any thoughts you might have are very welcome - I'm definitely eager to convert, but stuck. Many thanks!

**Comment by alxnbl** [comment]
Hey, OneNote for Windows 10 is not supported by the tool. I would recommend you to import your notebook on a computer with Office Suite Installed (OneNote + Word) and to then run the tool.
