### ISSUE TITLE
Page Ignored, Error Messege : 0x80042006

### ISSUE THREAD

**Issue by DadOfThree** [alxnbl/onenote-md-exporter#33]
Hi,

I've used this tool once before during my original OneNote to Joplin Migration.  I forgot a Notebook, and now trying to run the tool again.  However, I'm getting Page Ignored, Error Message : 0x80042006.

Any idea what that means?

**Comment by alxnbl** [comment]
Hi, could you check that MS Word is correctly installed, and ensure when you run it that no popup is displayed on startup.
Which version of the tool are you running ?

**Comment by DadOfThree** [comment]
Oh, that must be it. I created a Virtual Machine for Windows 10, and only installed OneNote by itself.  Thanks, I'll install and try again.

**Comment by DadOfThree** [comment]
Yup, that was the problem.  My fault, the documentation clearly says that I need word installed.  Thanks for pointing me in the right direction.

**Comment by alxnbl** [comment]
You're welcome. I will try to enhance error messages in a futur release.
