### ISSUE TITLE
Pages with same Title are skipped/overwritten in Markdown export mode

### ISSUE THREAD

**Issue by laggingreflex** [alxnbl/onenote-md-exporter#34]
**Describe the bug**

Pages in a Section with same Title are skipped. E.g.:

* Notebook 
  * Section
     * Page
         * Title
           * This is first random note
         * Title
           * This is second random note (with same title)

When exporting, there will only be 1 `Notebook\Section\Page\Title.md`

**To Reproduce**

In a Section create 2 pages with similar Title and export. 

**Expected behavior**

I know this is probably an obvious restriction naming the notes with <title>.md

Not sure what expected solution should be... perhaps adding (1), (2) to the end like Windows handles duplicate filenames?

There should definitely at least be a warning to alert the user. I only discovered it after a while. I was feeling quite satisfied when I felt I had successfully exported all my notes and may have gotten rid of original OneNote notebook and end up losing my notes... (lucky I didn't). So in my opinion there should definitely be a warning somewhere about this, as this can be quite an unexpected way to lose data. 

LOVE the project otherwise!

**Comment by alxnbl** [comment]
Thank you for the bug report!
I agree with you, It is an important issue because data are lost during export. I will solve this issue, probably as you suggested with a suffix number, in the next release.
