### ISSUE TITLE
Change releases build to single file mode

### ISSUE THREAD

**Issue by needs-coffee** [alxnbl/onenote-md-exporter#36]
related to #32 

Given the current iteration outputs the notebooks to the program folder it would be a good idea to change the provided built releases to export in single file mode so as to minimise the number of files in the folder and make the log file more obvious.

Also the releases executable file should probably be renamed to `OneNoteMdExporter.exe` from `alxnbl.OneNoteMdExporter.exe`

The *.pubxml I used is below which will output in single file mode. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Publish</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
</Project>
```

**Comment by alxnbl** [comment]
Thanks! I did not know how to output binaries into a single file. I will have a try in next few weeks as soon as I have free time.
