### ISSUE TITLE
No Files (except images) are exported in Markdown mode

### ISSUE THREAD

**Issue by laggingreflex** [alxnbl/onenote-md-exporter#38]
**Describe the bug**

A page with attached files, like audio/video/executable, are not exported in Markdown mode. 

**To Reproduce**

Attach a file on a page. Then export as Markdown mode.

**Expected behavior**

Files should be exported.

**Comment by alxnbl** [comment]
Thank you for the confirmation, I will try to fix it in the next few weeks.
