### ISSUE TITLE
Recorded Audio & Video are not exported

### ISSUE THREAD

**Issue by laggingreflex** [alxnbl/onenote-md-exporter#39]
**Describe the bug**

A page with recorded audio or video are not exported. The audio/video file don't 

Exported note appears as:

```md
*Screen clipping taken: 2021-06-19 11:27 AM*

Page.wmv

*Video recording started: 11:26 AM Saturday, 19 June, 2021*

Page.wma
```
There are no links to any files..

**To Reproduce**

Record a video or audio on a page. Then export. 

**Expected behavior**

It should export the recorded video/audio.

**Comment by alxnbl** [comment]
Thank you to submit this bug. I have tried to fix it but it actually comes from a OneNote behavior. For an obscure reason, OneNote refuse to export attachments of certain file extensions, at least  wma, wmv, mpg, svg, mp3. I will thus not been able to fix it.
