### ISSUE TITLE
Escaping dollar signs ($) in link titles

### ISSUE THREAD

**Issue by pmoseley** [alxnbl/onenote-md-exporter#47]
**Describe the bug**
In my OneNote notebooks, I have some external filesystem links that (weirdly/unfortunately/not-my-fault) have some $ in them.

After using the MD exporter with the raw Joplin format, it leads to a link that looks like this:
`[\\\\network_drive\\folder_with_dollar$\\child_folder](file:///\\network_drive\folder_with_dollar$\child_folder)`

In Joplin, this produces an error at the $, because it's trying to parse it as a LaTeX expression:
`KaTeX parse error: Undefined control sequence`

When I manually add an escape character for the $ in the title (not necessary in the actual link path) it renders correctly and the link correctly opens the desired directory when I click on it:
`[\\\\network_drive\\folder_with_dollar\$\\child_folder](file:///\\network_drive\folder_with_dollar$\child_folder)`

I'm not sure if this should be considered a Joplin bug instead? But since in any case OneNote doesn't support LaTeX rendering, it seems like the default behavior of the MD exporter should be to escape $ signs in all text regions.

**To Reproduce**

Create a OneNote page with an external link to a folder with a $ in the name.
Export to raw joplin.
Import to Joplin. The link will give an error.

**Expected behavior**
The link should appear visually as it does in OneNote, which means that the `$` should be escaped to `\$`.

**Desktop (please complete the following information):**
 - Windows version : Windows 10 Pro 64 bits
 - Office Version : 2013 64 bits

**Additional context**
I haven't checked to see if the $ works correctly in other contexts, for example in plain text.

In any case, thanks for this tool, it worked extremely well for me! This minor bug has not prevented me from making the switch.

**Comment by alxnbl** [comment]
Thank you for this detailed report. I will fix it as son as I get  some free time.

**Comment by alxnbl** [comment]
I reviewed your issue I am not sur too if it should be considered as a bug of Joplin or not. I double checked and PanDoc is already escaping some markdown special chars like '*' et '_'. So I don't want to try to implement a fix. It would be tricky to implement and could lead to issue like double escaping some chars. Thank again for the report.
