### ISSUE TITLE
Why is Word needed?

### ISSUE THREAD

**Issue by sbn-purchark** [alxnbl/onenote-md-exporter#50]
I guess this won't work with just the standalone MS365 Desktop Onenote installation? When you say free application I thought you just meant the "OneNote for Windows 10" UWP app.

```
Press [Enter] to continue...

Unhandled exception. System.Runtime.InteropServices.COMException (0x80029C4A): Error loading type library/DLL. (0x80029C4A (TYPE_E_CANTLOADLIBRARY))
```

**Comment by alxnbl** [comment]
That's true, the export process is converting notes into an intermediate docx file that requires both OneNote and Word to be installed. I never tried it but you can install evaluation version of Word if your licence do not includes it.

**Comment by alxnbl** [comment]
An alternative would be to export in an intermediate format other than docx, like html, but the tool dot not support it yet.

**Comment by sbn-purchark** [comment]
I tried a tool in the past that went MS cloud API --> html --> pandoc MD. Result was terrible. I'll look for a copy of Word. Thanks!

**Comment by alxnbl** [comment]
You're welcome, hope you will be satisfied with the result!
