### ISSUE TITLE
For image inside tables <img src = ":/idtoimagebalabala" alt="imagename"> instead of [!imagename](:/idtoimagebalabala)

### ISSUE THREAD

**Issue by TIE666** [alxnbl/onenote-md-exporter#54]
Hi,

I personally use image inside table to get my note organised, however after converting, the markdown notion does not render correctly, I try changing it to the tag version and it worked. So whether the converting process could be change a bit, so whenever there's a image inside table, use `<img src = ":/idtoimagebalabala" alt="imagename">` instead of `[!imagename](:/idtoimagebalabala)` .

Huge thanks

**Comment by alxnbl** [comment]
Hello @TIE666 and thank you for the feedback, the issue is already identified here #48 . 

As a workaround, you may be interested to set the setting "PostProcessingMdImgRef" to false to disable the replacement of IMG tag by markdown references. Note it will affect all IMG tag, not only the ones nested in tables.

**Comment by TIE666** [comment]
Hi,

I find a time to come back to this issue, and figure out a trick to allow images in the tables, while it seems have no side effect on others.

So I modify line 301 in OneNoteMdExporter\Services\Export\ExportServiceBase.cs
`return $"![{refLabel}]({attachRef})";`
to
`return $"<img src=\"{attachRef}\" alt=\"{refLabel}\">";`

Please feel free to use it in the next version if this help. 
Now only extra thing to make my conversion perfect (like what it look like in Onenote) is to handle the resized image in Onenote, as the current conversion ignores the resize done in Onenote.

**Comment by alxnbl** [comment]
Thank you for the feedback! I opened a feature request for #64 .
