### ISSUE TITLE
.net build instructions

### ISSUE THREAD

**Issue by warrantyvoid-0x90** [alxnbl/onenote-md-exporter#6]
I figured it out but the readme could use some instructions on .netbuild if there isn't going to be a binary distribution

**Comment by alxnbl** [comment]
Hi @warrantyvoid-0x90, there is binary distribution in the Releases page of the repo : https://github.com/alxnbl/onenote-md-exporter/releases . I will complete the documentation to add instructions to build the app and link to the releases page.
