### ISSUE TITLE
导出Mark文件时为什么没有把图片也导出来

### ISSUE THREAD

**Issue by DoYou-007** [alxnbl/onenote-md-exporter#66]

**Comment by XFbeibei** [comment]
Here's what's on my OneNote note
![image](https://user-images.githubusercontent.com/46665036/177323909-d21d9e4c-1211-419d-9e99-a94be5fc4793.png)
This is the content after export
![image](https://user-images.githubusercontent.com/46665036/177324043-44f53f77-5559-4f4d-bd77-cdcb2f1e999e.png)

My expectation is that the image can also be loaded normally after exporting to an md file; are there any configuration parameters that need to be set?吗？

**Comment by XFbeibei** [comment]
@alxnbl

**Comment by alxnbl** [comment]
I don't see anything wrong with your export. The MD file contains references to images that should be displayed correctly when rendering the display view of the page in your MD editor. Which editor are you using?
