### ISSUE TITLE
"AddFrontMatterHeader": true – does not add front matter

### ISSUE THREAD

**Issue by dreamflasher** [alxnbl/onenote-md-exporter#67]
**Describe the bug**
I have `"AddFrontMatterHeader": true,` in the settings file, but the export does not contain any front matter.

**To Reproduce**

Steps to reproduce the behavior.
Add `"AddFrontMatterHeader": true,` to your config file, export.

**Expected behavior**
Have a front matter in every note.

**Logs**
The logs don't contain any interesting info. I'll create an issue for adding some more relevant log info.

**Desktop (please complete the following information):**
 - Windows version : 10
 - Office Version : 2021

**Comment by alxnbl** [comment]
Hey, I do not reproduce the issue with version 1.2. And I don't expect this bug to be related to Windows or Office environment.
Could you make a new try and if you reproduce join your setting file.
