### ISSUE TITLE
Add relevant log info to logs

### ISSUE THREAD

**Issue by dreamflasher** [alxnbl/onenote-md-exporter#68]
**Describe the bug**
Currently the log is mostly useless, as it does not contain at least:
* version details requested here in the ticket: Windows version, Office version, and I'd also suggest to add OnenoteMdExporter version
* The full OnenoteMdExporter config (including implicit parameters) that's currently running → with this it would be possible to see if the config is correctly taken up (currently it looks like all config params are ignored)

**Comment by alxnbl** [comment]
Hey @dreamflasher and that you for your feedback.
I distinguish two distinct log kinds : 
- Technical execution logs : which give details on the behavior of the app during the export, especially when something get wrong
- Device diagnostic logs : which give information about the device on which the tool is running
- 
The log.txt file aim only at being a technical execution logs. I agree that a device diagnostic log would be helpful too, but right no it is no a priority for me. The workaround is relying on each user to get these info and describe them in the git issue description.

Open to any PR if you are interested in ;).
