### ISSUE TITLE
Where is the OneNoteMdExporter.exe?

### ISSUE THREAD

**Issue by DadOfThree** [alxnbl/onenote-md-exporter#7]
Hi, 
I'm new here and making my exit from Microsoft products.  Onenote is the last thing I'm having issues migrating off of.  I'd like to try this tool as I"m looking to test out Joplin.  Under the usage area, it says to "Start OneNoteMdExporter.exe".  I've installed the prerequisites.  After downloading the files, I'm not seeing a OneNoteMdExporter.exe?

Am I misunderstanding how all this is supposed to work?

**Comment by alxnbl** [comment]
Hi @DadOfThree, after downloading the OneNoteMdExporter.v0.2.zip, you need to extract content of the zip file and then you should find the "alxnbl.OneNoteMdExporter.exe" file to execute. I will precise the documentation on that point.
Does it work for you ?

**Comment by DadOfThree** [comment]
Yes, I extracted the zip, but I don't see any extensions that say .exe.  All I see is, .csproj, .sln, .json, .cs.
Maybe I'm not understanding how the app is supposed to be executed?  I'm on a Windows 10 machine and new to github.

**Comment by alxnbl** [comment]
Yes, I think you have downloaded the source of the repository, note the binary release. That is why you don't find any ".exe" file.
From the "Releases" page of the repository ([here](https://github.com/alxnbl/onenote-md-exporter/releases)), you need to download the last "binaries" of the app : OneNoteMdExporter.v0.2.zip

**Comment by DadOfThree** [comment]
Quick question.  When referring to Notes, what does Markdown mean?

**Comment by alxnbl** [comment]
To Markdown language, more here : https://joplinapp.org/markdown/ .

**Comment by DadOfThree** [comment]
Wow!  Just......... Wow!

I've tried a few other methods with limited results before finding this script.  This works VERY well.  Nice job developers., NICE JOB ineed!

**Comment by alxnbl** [comment]
Thanks, happy if it did the job for you!
