### ISSUE TITLE
Possible to run on Mac with powershell?

### ISSUE THREAD

**Issue by mbbroberg** [alxnbl/onenote-md-exporter#70]
I'd love to run this software but only have Macs on hand. Then I saw [powershell runs on MacOS](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2) these days. Is there anyone out there running this on this other OS?

**Comment by alxnbl** [comment]
Hi, @mbbroberg , the tool rely on a component part of MS Office called "Interop" that is missing on Mac and will thus not work (cf this post https://stackoverflow.com/questions/41172984/office-excel-com-interop-on-mac-osx-using-net-core ).


I can suggest you two alternatives :

Altrernative 1 : Run the OneNoteMdExporter tool on an other Windws computer 
- Export your notebooks in onepkg format (cf https://github.com/alxnbl/onenote-md-exporter/blob/main/doc/notebook-onepkg-export.md), copy it on a Windows computer that you trust with Office installed , import the notebooks, run the OnenodeMdExport tool then remove notebooks from OneNote.
Nb: I never tried to export from Mac, to be tested

Alternative 2 : Look for an alternative export tool that rely on Microsoft cloud API
- Microsoft provides a service that allows to export notebooks preciously synchronized with a Microsoft Account. Maybe you can found a tool running on Mac that use this API ? Similar to this one : https://gist.github.com/Danmou/46e21b0c7090cb27425fa389f5102b16

Any feedback of the solution you will find is warmly welcome!
