### ISSUE TITLE
Working in reverse?  (ie export Joplin to Evernote)

### ISSUE THREAD

**Issue by jongbray** [alxnbl/onenote-md-exporter#71]
Would this be possible please?   I migrated from Evernote to Joplin and really it, but despite trying most of the sync options I find that syncing between mobile and desktop is highly dodgy

**Comment by alxnbl** [comment]
Hey, the tool is limited to export from OneNote into markdown and Joplin format.
If you want to switch from Joplin to Evernote the tool is not useful for yo. 
One solution could have been to export your Joplin notes into markdown and import them in Evernote, but it seams that Evernote do not support it.
An other solution could be to export from Joplin into markdown, then import note into a notes app that support markdown import and than is supported by Evernote import.

Hope it can help you.

**Comment by jongbray** [comment]
Yeah, I might look at the second option, thanks.
