### ISSUE TITLE
Add a setting to to configure the max length of a page title before truncation

### ISSUE THREAD

**Issue by windwhirl94** [alxnbl/onenote-md-exporter#72]
**Describe the bug**
The title of any OneNote page will be truncated if it exceeds 50 characters. I have verified the md files, and the title is truncated in them right off the bat, so it's safe to discard any issues in the destination application (Joplin in my case)

**To Reproduce**
Steps to reproduce the behavior.

Either make a new Onenote notebook or use an old one, give a page any title that exceeds 50 characters, process it through Onenote MD Exporter, import to Joplin or any other destination. The page contents are exported fine (at least I've never encountered an issue in that regard), but the title is always truncated to 50 characters plus ellipsis.

**Expected behavior**
The page title should be exported without being truncated, or there should be a setting to configure if the title should be truncated (and in that case, preferentially be able to configure the maximum length).

**Logs**
Join the "logs.txt" log file located in the directory of the tool. 
⚠️ Ensure that the log file do not contain any personal data ⚠️
[logs - Copy.txt](https://github.com/alxnbl/onenote-md-exporter/files/9757558/logs.-.Copy.txt)

**Desktop (please complete the following information):**
 - Windows version : Windows 11 64 bits
 - Office Version : Office 365 64 bits version 2211, build 15729.20002

**Additional context**
I've added a ZIP file containing the Onenote notebook and the export results, if it's of any use.
[test.zip](https://github.com/alxnbl/onenote-md-exporter/files/9757644/test.zip)

**Comment by alxnbl** [comment]
Thank you for the report, I will try to fix this in the next version.

**Comment by alxnbl** [comment]
Implemented in version 1.3.0 :)
