### ISSUE TITLE
Upgrading to .NET 6

### ISSUE THREAD

**Issue by kevinram** [alxnbl/onenote-md-exporter#73]
I am not suggestion you merge my fork.  I didn't modify to code correctly for a pull request.  BUT, do you have plans to upgrade the code to the latest .NET?  Because the new syntax allowed me to simplify the namespaces.  Its much easier to read now.

**Comment by alxnbl** [comment]
Hey Kevin, indeed I need to find some time to move the project to DotNet6, the version 5 is no longer supported for a while. Hopefully by the end of the year!

**Comment by alxnbl** [comment]
Implemented in version 1.3.0
