### ISSUE TITLE
Weird export folders created and media stripped from pages 

### ISSUE THREAD

**Issue by thorrrr** [alxnbl/onenote-md-exporter#78]
Hi
More of a question i followed the instructions per the docs on the latest version  on 05/12/2022 .
It made a folder on import i got a lot of high level folders not required that had my folders a 4 levels down
I also noticed all the images from my pages had been stripped from every page and placed in a media folder ???????
What am i doing wrong ?

**Comment by alxnbl** [comment]
Hey @thorrrr , could you give more details about the folder hierarchy produced by the export ? Join a capture or zip of the folder hierarchy. Thanks.
