### ISSUE TITLE
Halfway through the process, it cannot continue

### ISSUE THREAD

**Issue by SKDDJ** [alxnbl/onenote-md-exporter#79]
**Describe the bug**
**After a certain number of files have been converted, the program does not proceed with the conversion**
**To Reproduce**

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : 1.2.0.0
 - Windows version : Win 11 64 bits
 - Office Version : latest 64 bits

**Comment by alxnbl** [comment]
Hello @SKDDJ , please guive additonal data, like a sample Notebook export and a copy of the logs.

**Comment by SKDDJ** [comment]
> Hello @SKDDJ , please guive additonal data, like a sample Notebook export and a copy of the logs.

Sorry @alxnbl , I've found how to solve this problem. Some **plugins** in my Word cause this error, so I _kill the process of word_ when there happened some errors. And I've converted my notes yet. Thank you alxnbl :smile:

**Comment by alxnbl** [comment]
OK, thanks for the feedback
