### ISSUE TITLE
Export doesn't include pages

### ISSUE THREAD

**Issue by J8cob1** [alxnbl/onenote-md-exporter#82]
**Describe the bug**
The export doesn't seem to work at all, for any page. All the pages error out, but the notebooks are there.

**To Reproduce**

(for this example, I exported one notebook)

Steps to reproduce the behavior.
1. Run the program
2. **select a notebook**
3. [2] Joplin Raw Folder
4. [Enter]

**Expected behavior**
The export should include both the pages and the notebook itself.

**Logs**
[logs-file.txt](https://github.com/alxnbl/onenote-md-exporter/files/10833163/logs-file.txt)

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : 1.3.0
 - Windows version : 10.0.22621 Build 22621 64 bits (Windows 11 64 bit)
 - Office Version : 18.2301.1131.0 64 bits

**Additional context**

Errors look like this:
   Page 2/2 : To-Do
Page '******\Work\To-Do': Error during processing of page To-Do [3c0f700bf9c04d20979648fdc38cf7c7]. Page ignored. Error message : 0x80042006

**Comment by alxnbl** [comment]
Hey @J8cob1 , you can try to reproduce with a dummy notebook with two or the dummy pages.
If the error still occurs, it's probably an issue with your OneNote installation. You can try to uninstall/reinstall or repair your office installation.

**Comment by J8cob1** [comment]
I tried reinstalling and creating a dummy notebook. The result is the same for me

**Comment by alxnbl** [comment]
OK, so it an issue specific to your system. I would suggest to try to export from an on other computer...
