### ISSUE TITLE
Not really a bug but something to be aware of.

### ISSUE THREAD

**Issue by doobes** [alxnbl/onenote-md-exporter#88]
So,

I've got (or had) my command window set to a white background with black texts.

Running the exporter I'm faced with a blank white screen....

After some to-ing and fro-ing I realize the exporter is hard coded to use white text, which made the text "invisible".

Changing the command window to black background and white text, and voila! It works just peachy.

Thanks for the app by the way!

cheers

chris

**Comment by alxnbl** [comment]
Thank you for the feedback. Surprising, the color of the text is the by-default value, and I would expect Windows to manage that out-of-the-box.
