### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by doobes** [alxnbl/onenote-md-exporter#89]
I used the exporter to export a plethora of OneNote notebooks

Not a single image/pdf in any of the notebooks was available upon import to Joplin.

I exported the notebooks as Joplin Raw Folders and then imported the same way into Joplin.

What am i doing wrong?

**Comment by alxnbl** [comment]
Hi, could you give more detail about the folder in which you exported your notes and some capture of how you do the import in joplin. Thanks.
