### ISSUE TITLE
Images not being exported for Notebook with apostrophe

### ISSUE THREAD

**Issue by J-SHarper** [alxnbl/onenote-md-exporter#90]
**Describe the bug**
Images are not being exported for some reason. 
**To Reproduce**

Steps to reproduce the behavior.
Attempt to export any of my notebooks. 
All of the images fail with the below error. No other errors are logged.

**Expected behavior**
I hoped images would be exported.

**Logs**
Here is the error: `[15:49:21 WRN] Page 'Joshua's Notebook\Quick Notes\Photo IMG_8689': Error while extracting images of the page.` Nothing else seems out of the ordinary. Happy to private message the logs file to anyone who can help.

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : 1.3.0
 - Windows version : 11 Pro 64 bits
 - Office Version : 2307 64 bits

**Additional context**
Failed across all of my notebooks.

**Comment by alxnbl** [comment]
Thank for your report. Sorry but I will be very busy the next few months and will not be able to have a look to the issue. Hopefully, a kind contributor will take a look at your problem.

**Comment by mgelmantech** [comment]
I found that removing the apostrophe (i.e. "Michaels's Notebook" -> "Michaels Notebook") fixed this issue for me.  I suspect there's something going on with the character conversion in the path somewhere but I was unable to track it down in the short period of time I had to look at it.

**Comment by alxnbl** [comment]
Thanks a lot a for the feedback. I will try to solve the issue in the next version of the tool*.

**Comment by alxnbl** [comment]
Related to #80

**Comment by alxnbl** [comment]
I did not managed to reproduce the bug. Do you mind to send me a sample Onenote notebook that cause the crash to append ?
Thanks

**Comment by armstrong-pv** [comment]
Hi, I created a PR fix for this, as it happened with my notebook, titled: Paul's Notebook. I think any 'special' HTML character would cause the issue, as this got translated to: "C:\\Users\\Paul\\AppData\\Local\\Temp\\Paul&#39;s Notebook\\pandoc\\media\\image1.png"
PR fix:

**Comment by alxnbl** [comment]
Thanls a lot for the PR, I will review it as soon as possible.

**Comment by alxnbl** [comment]
Thanks again to reproduce and fix the bug @armstrong-pv ! The fix is embedded in version 1.4.
