### ISSUE TITLE
Error on running program

### ISSUE THREAD

**Issue by James-Oakley** [alxnbl/onenote-md-exporter#92]
Hi, I'm getting an error trying to run onenote-md-exporter.

```
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
   at alxnbl.OneNoteMdExporter.Program.RunOptions(Options opts) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 66
   at alxnbl.OneNoteMdExporter.Program.<>c.<Main>b__2_0(Options options) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 54
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at alxnbl.OneNoteMdExporter.Program.Main(String[] args) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 47
```

I've looked at the source code, and the cast is from here

```
public static OneNote.Application OneNoteApp;
OneNoteApp = new OneNote.Application();
```

So I'd guess that the constructor hasn't returned an instance of OneNote.Application.

I am running OneNote as part of Office Standard 2019 - version 1808 and build 10401.20025 Click-to-run.

I've tried running Quick Repair from the Apps & features screen, but it still throws the same error.

Any suggestions?

**Comment by alxnbl** [comment]
Thank for this first analysis. I would suspect that your installation of office present an issue.
What does mean "Clic-to-run" ?

**Comment by James-Oakley** [comment]
It's how Microsoft did volume licensing from the 2019 edition onwards. Instead of getting a CD, you have to use a download tool from their website with a configuration xml file that tells it which components of office you want, whether you want x86 or x64, and a few other options - it then downloads and installs Office. But the result is a full offline edition of Office, just with a different installation flow. I think it's in some ways similar to how they do Office 365, but I've never used that so can't be sure.

**Comment by alxnbl** [comment]
OK, maybe you can try either to uninstall + reinstall office, or to install it and runit on an other computer ? Not sur if you can execute the export without having done the product activation.

**Comment by James-Oakley** [comment]
Just to let you know, I wasn't able to install 2 versions of office on the same computer (you can't mix and match Click2Run and MSI installations). So I fired up a Windows VM and installed Office 2016. No need to activate Windows 10 or Office to get this to work, so can do it and then delete the installation when I'm done. It's all working fine.

So in terms of me asking for help to get started, I'm now able to run my export.

In terms of feature requests going forwards, I think .net interop works with click2run installations from what I've read, but there must be something that needs doing differently. Microsoft are steadily pushing everything away from MSI and over to C2R, so this will be something others will need.

Thanks for your help

**Comment by alxnbl** [comment]
Glad you manage to carry out the export.
A quick research on some forum let me think that C2r installation should be working without any additional development and your issue could be specific to your setup. But it is only a supposition.

**Comment by tridian-tn** [comment]
Hi there. I appreciate this issue is closed but just wanted to contribute my experience: my OneNote is also "click-to-run", and I had the same error as @James-Oakley. I'll follow the VM route. Cheers.

**Comment by tridian-tn** [comment]
Sorry one more thing to add, just for info - I ran the solution in Visual Studio (same version as the built release) and it worked fine. No casting error

**Comment by James-Oakley** [comment]
> Sorry one more thing to add, just for info - I ran the solution in Visual Studio (same version as the built release) and it worked fine. No casting error

Out of interest, did you try recompiling it, then running the version you'd compiled as a stand-alone .NET executable (not running within Visual Studio?)

**Comment by tridian-tn** [comment]
> Out of interest, did you try recompiling it, then running the version you'd compiled as a stand-alone .NET executable (not running within Visual Studio?)

I've just tried running a debug and release build outside VS and it worked in both cases. Very very weird!
