### ISSUE TITLE
Can I customize the storage path?

### ISSUE THREAD

**Issue by cyx951211** [alxnbl/onenote-md-exporter#95]
Can I customize the storage path?

**Comment by cyx951211** [comment]
> Can I customize the storage path?我可以自定义存储路径吗？

Secondly, I moved the downloaded MD, and the picture was not indexed

**Comment by alxnbl** [comment]
Hey @cyx951211 , please give a more detailed description of what your are trying to do. Difficult to help you with so few information. If you want to report a bug, please respect the bug report template.
