### ISSUE TITLE
OneNotes notes with folded/collapsed areas not converted

### ISSUE THREAD

**Issue by SomeMichael** [alxnbl/onenote-md-exporter#99]
**Describe the bug**
When one uses folding/collapsing in OneNote onenote-md-exporter misses the folded/collapsed content when converting.
OneNote-Example:
![OneNote](https://github.com/alxnbl/onenote-md-exporter/assets/43578183/b918828b-b319-4127-9288-50ed961a8489)

Results:
Folded content is not included.
![Joplin_Folded](https://github.com/alxnbl/onenote-md-exporter/assets/43578183/a5a30b11-bee9-4d79-bdab-f2ac531207ad)
![Joplin_Unfolded](https://github.com/alxnbl/onenote-md-exporter/assets/43578183/c3e854fb-0b1b-4f54-81b9-aab80018cb3b)

**To Reproduce**
Convert the following OneNote file:
[Test_OneNote2Joplin.zip](https://github.com/alxnbl/onenote-md-exporter/files/14297481/Test_OneNote2Joplin.zip)

**Expected behavior**
Also convert content in the folded sections.

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : v1.3.0, v1.4.0
 - Windows version : Windows 11 64 bits
 - Office Version : Office Pro Plus 2016 

**Additional context**
I tried to find a way to automatically unfold these section looking [here](https://learn.microsoft.com/en-us/office/client-developer/onenote/application-interface-onenote), but couldn't find anything (But I'm not an expert one these things :))
It might be possible using [getonetastic](https://getonetastic.com/)?
My problem is that my OneNote collection of Notes is quite big. Resulting in 7000 files (also attachments included, though) on Joplin side. So checking everything manually is some work... ;-)

Many thanks for any kind of help!

**Comment by alxnbl** [comment]
Hello @SomeMichael , thank you for the detailed feedback.
Indeed I knew this limitation which comes from a behavior of OneNote API. I don't think I will have time to determine if and how it would be possible to unfold automatically paragraph during page export.
However in your case, as you suggested, find a OneNote plugin that can do that for you seams a good approach. I don't know much theses plugins, but maybe you can find help on some OneNote community forums like https://www.reddit.com/r/OneNote/ .

**Comment by SomeMichael** [comment]
Thanks for your answer, @alxnbl. I think will getonetastic a try, then.

Maybe it would be a good idea to add this limitation [here](https://github.com/alxnbl/onenote-md-exporter?tab=readme-ov-file#features-and-limitations)?

**Comment by alxnbl** [comment]
Indeed, I added the limitation to the readme !

**Comment by SomeMichael** [comment]
Just if anyone runs into the same issue and finds this thread. I came up with this Powershell script to expand all outlines in a notebook:

```
$OneNote = New-Object -ComObject OneNote.Application

[string]$nbid = ""
[xml]$nbh = ""

$OneNote.OpenHierarchy('FullPath2NotebookFolder', "", [ref]$nbid)
$OneNote.GetHierarchy($nbid, [Microsoft.Office.Interop.OneNote.HierarchyScope]::hsPages, [ref]$nbh)

foreach ($page in $nbh.Notebook.Section.Page ) {

    $page.ParentNode.Name + " " + $page.Name
    
    [xml]$pagexml = ""
    $OneNote.GetPageContent($page.ID, [ref]$pagexml)

    $write = ""
    foreach ($el in $pagexml.GetElementsByTagName("one:OE")) {
        
        if ($el.collapsed -eq "1") {

            Write-Host "	Outline expanded!"
            $el.removeAttribute("collapsed")
            $write = "updatepage"

        }
    }

    if ($write -ne "") {
        $OneNote.UpdatePageContent($pagexml.OuterXml.ToString())
    }
}
```

Replace _FullPath2NotebookFolder_ with the full path to the folder containing the *.one files of your notebook!

Please run this script using Powershell 5.\* . Powershell 6 and above have issues explained [here](https://impsbl.hatenablog.jp/entry/OneNoteAndPowerShell_en). I couldn't figure out how to get it running in Powershell 7.\*.

**Please make a backup of your \*.one files prior to running the script!** I'm not a very experienced programmer, so expect some errors when you run the script ;-)

**Comment by alxnbl** [comment]
Thanks @SomeMichael , @Argimko made a Pull Request to support unfolding of paragraph 🎉. The evolution is embedded in version 1.5.0.
